image: node:11

stages:
  - build
  #- test
  - deploy

build_debug:
  #only:
  #- master
  before_script:
    # Install node_modules needed to build the app
    - npm install
    # Install fastlane
    - bundle update
  script:
    - npm run build
    - bundle exec fastlane android build_debug

deploy:
  only:
    - tags
  before_script:
    ##
    ## Install node_modules needed to build the app
    - npm install
    ##
    ## Install fastlane
    - bundle update

  script:
    - npm run build

    - node scripts/sentry.js

    # TODO: have 3 seperate build/deploy jobs in order to run in parallell
    - bundle exec fastlane android build
    - bundle exec fastlane android deploy

    - bundle exec fastlane ios build
    - bundle exec fastlane ios deploy
